project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: 'Home'
      - href: portfolio.qmd
        text: 'Work Samples'
      - href: resume.qmd
        text: 'Resume'
    right:
        - icon: linkedin
          href: https://www.linkedin.com/in/richard-barad-70b70277/
        - icon: github
          href: https://github.com/richardbarad
        - icon: envelope
          href: mailto:richard.barad@gmail.com

page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; cc-Richard Barad, 2024"
        
format:
  html:
    highlight-style: solarized
    theme: cosmo




